"""Initial schema

Revision ID: d675b5d4a7e3
Revises: 
Create Date: 2026-08-01 13:03:30.014665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd675b5d4a7e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_roles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_roles_name'), 'app_roles', ['name'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_assignments_zone_id'), 'assignments', ['zone_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_id', sa.String(length=120), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('attachment_type', sa.String(length=80), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_attachment_type'), 'attachments', ['attachment_type'], unique=False)
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachments_local_id'), 'attachments', ['local_id'], unique=False)
    op.create_index(op.f('ix_attachments_sync_status'), 'attachments', ['sync_status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.String(length=40), nullable=True),
    sa.Column('end_date', sa.String(length=40), nullable=True),
    sa.Column('zone_ids', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('chat_group_members',
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('chat_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('receiver_id', sa.String(length=64), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('reply_to', sa.String(length=64), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_receiver_id'), 'chat_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_id', sa.String(length=120), nullable=True),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('document_number', sa.String(length=120), nullable=False),
    sa.Column('issue_date', sa.String(length=40), nullable=True),
    sa.Column('expiry_date', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_local_id'), 'documents', ['local_id'], unique=False)
    op.create_index(op.f('ix_documents_person_id'), 'documents', ['person_id'], unique=False)
    op.create_table('duplicate_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_a_id', sa.String(length=64), nullable=False),
    sa.Column('person_b_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_candidates_created_at'), 'duplicate_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_person_a_id'), 'duplicate_candidates', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_person_b_id'), 'duplicate_candidates', ['person_b_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_status'), 'duplicate_candidates', ['status'], unique=False)
    op.create_table('family_relations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_id', sa.String(length=120), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('source_person_id', sa.String(length=64), nullable=False),
    sa.Column('target_person_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=80), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.String(length=40), nullable=True),
    sa.Column('end_date', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_relations_campaign_id'), 'family_relations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_family_relations_relation_type'), 'family_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_family_relations_source_person_id'), 'family_relations', ['source_person_id'], unique=False)
    op.create_index(op.f('ix_family_relations_sync_status'), 'family_relations', ['sync_status'], unique=False)
    op.create_index(op.f('ix_family_relations_target_person_id'), 'family_relations', ['target_person_id'], unique=False)
    op.create_index(op.f('ix_family_relations_validation_status'), 'family_relations', ['validation_status'], unique=False)
    op.create_index(op.f('ix_family_relations_zone_id'), 'family_relations', ['zone_id'], unique=False)
    op.create_table('faq_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_definitions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_definitions_status'), 'form_definitions', ['status'], unique=False)
    op.create_table('form_responses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('form_definition_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_campaign_id'), 'form_responses', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_form_responses_form_definition_id'), 'form_responses', ['form_definition_id'], unique=False)
    op.create_index(op.f('ix_form_responses_sync_status'), 'form_responses', ['sync_status'], unique=False)
    op.create_index(op.f('ix_form_responses_validation_status'), 'form_responses', ['validation_status'], unique=False)
    op.create_index(op.f('ix_form_responses_zone_id'), 'form_responses', ['zone_id'], unique=False)
    op.create_table('geographic_zones',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geographic_zones_code'), 'geographic_zones', ['code'], unique=True)
    op.create_index(op.f('ix_geographic_zones_parent_id'), 'geographic_zones', ['parent_id'], unique=False)
    op.create_index(op.f('ix_geographic_zones_status'), 'geographic_zones', ['status'], unique=False)
    op.create_index(op.f('ix_geographic_zones_type'), 'geographic_zones', ['type'], unique=False)
    op.create_table('home_content',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('nav_links', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('hero', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('footer', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('households',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_id', sa.String(length=120), nullable=True),
    sa.Column('household_code', sa.String(length=120), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('head_person_id', sa.String(length=64), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('housing_type', sa.String(length=120), nullable=True),
    sa.Column('occupancy_status', sa.String(length=120), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_campaign_id'), 'households', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_households_household_code'), 'households', ['household_code'], unique=False)
    op.create_index(op.f('ix_households_local_id'), 'households', ['local_id'], unique=False)
    op.create_index(op.f('ix_households_sync_status'), 'households', ['sync_status'], unique=False)
    op.create_index(op.f('ix_households_validation_status'), 'households', ['validation_status'], unique=False)
    op.create_index(op.f('ix_households_zone_id'), 'households', ['zone_id'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_id', sa.String(length=120), nullable=True),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('condition_name', sa.String(length=180), nullable=False),
    sa.Column('condition_code', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('diagnosis_age', sa.Integer(), nullable=True),
    sa.Column('diagnosis_date', sa.String(length=40), nullable=True),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('hereditary_risk', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_histories_campaign_id'), 'medical_histories', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_medical_histories_category'), 'medical_histories', ['category'], unique=False)
    op.create_index(op.f('ix_medical_histories_condition_code'), 'medical_histories', ['condition_code'], unique=False)
    op.create_index(op.f('ix_medical_histories_condition_name'), 'medical_histories', ['condition_name'], unique=False)
    op.create_index(op.f('ix_medical_histories_hereditary_risk'), 'medical_histories', ['hereditary_risk'], unique=False)
    op.create_index(op.f('ix_medical_histories_local_id'), 'medical_histories', ['local_id'], unique=False)
    op.create_index(op.f('ix_medical_histories_person_id'), 'medical_histories', ['person_id'], unique=False)
    op.create_index(op.f('ix_medical_histories_severity'), 'medical_histories', ['severity'], unique=False)
    op.create_index(op.f('ix_medical_histories_status'), 'medical_histories', ['status'], unique=False)
    op.create_index(op.f('ix_medical_histories_sync_status'), 'medical_histories', ['sync_status'], unique=False)
    op.create_index(op.f('ix_medical_histories_validation_status'), 'medical_histories', ['validation_status'], unique=False)
    op.create_index(op.f('ix_medical_histories_zone_id'), 'medical_histories', ['zone_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('local_id', sa.String(length=120), nullable=True),
    sa.Column('household_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('other_names', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.String(length=40), nullable=True),
    sa.Column('birth_date_estimated', sa.Boolean(), nullable=False),
    sa.Column('estimated_age', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.String(length=160), nullable=True),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('primary_language', sa.String(length=120), nullable=True),
    sa.Column('marital_status', sa.String(length=80), nullable=True),
    sa.Column('occupation', sa.String(length=160), nullable=True),
    sa.Column('education_level', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('is_without_document', sa.Boolean(), nullable=False),
    sa.Column('data_source_type', sa.String(length=80), nullable=True),
    sa.Column('vital_status', sa.String(length=40), server_default='ALIVE', nullable=False),
    sa.Column('death_date', sa.String(length=40), nullable=True),
    sa.Column('death_place', sa.String(length=160), nullable=True),
    sa.Column('cause_of_death', sa.String(length=160), nullable=True),
    sa.Column('residency_status', sa.String(length=40), nullable=True),
    sa.Column('arrival_date', sa.String(length=40), nullable=True),
    sa.Column('departure_date', sa.String(length=40), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_campaign_id'), 'persons', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_persons_first_name'), 'persons', ['first_name'], unique=False)
    op.create_index(op.f('ix_persons_gender'), 'persons', ['gender'], unique=False)
    op.create_index(op.f('ix_persons_household_id'), 'persons', ['household_id'], unique=False)
    op.create_index(op.f('ix_persons_last_name'), 'persons', ['last_name'], unique=False)
    op.create_index(op.f('ix_persons_local_id'), 'persons', ['local_id'], unique=False)
    op.create_index(op.f('ix_persons_phone'), 'persons', ['phone'], unique=False)
    op.create_index(op.f('ix_persons_sync_status'), 'persons', ['sync_status'], unique=False)
    op.create_index(op.f('ix_persons_validation_status'), 'persons', ['validation_status'], unique=False)
    op.create_index(op.f('ix_persons_zone_id'), 'persons', ['zone_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('zone_ids', sa.JSON(), nullable=False),
    sa.Column('password_changed_at', sa.String(length=40), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferred_language', sa.String(length=10), server_default='fr', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_persons_zone_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_validation_status'), table_name='persons')
    op.drop_index(op.f('ix_persons_sync_status'), table_name='persons')
    op.drop_index(op.f('ix_persons_phone'), table_name='persons')
    op.drop_index(op.f('ix_persons_local_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_last_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_household_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_gender'), table_name='persons')
    op.drop_index(op.f('ix_persons_first_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_campaign_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_medical_histories_zone_id'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_validation_status'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_sync_status'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_status'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_severity'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_person_id'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_local_id'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_hereditary_risk'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_condition_name'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_condition_code'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_category'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_campaign_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_households_zone_id'), table_name='households')
    op.drop_index(op.f('ix_households_validation_status'), table_name='households')
    op.drop_index(op.f('ix_households_sync_status'), table_name='households')
    op.drop_index(op.f('ix_households_local_id'), table_name='households')
    op.drop_index(op.f('ix_households_household_code'), table_name='households')
    op.drop_index(op.f('ix_households_campaign_id'), table_name='households')
    op.drop_table('households')
    op.drop_table('home_content')
    op.drop_index(op.f('ix_geographic_zones_type'), table_name='geographic_zones')
    op.drop_index(op.f('ix_geographic_zones_status'), table_name='geographic_zones')
    op.drop_index(op.f('ix_geographic_zones_parent_id'), table_name='geographic_zones')
    op.drop_index(op.f('ix_geographic_zones_code'), table_name='geographic_zones')
    op.drop_table('geographic_zones')
    op.drop_index(op.f('ix_form_responses_zone_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_validation_status'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_sync_status'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_form_definition_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_campaign_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_form_definitions_status'), table_name='form_definitions')
    op.drop_table('form_definitions')
    op.drop_table('faq_items')
    op.drop_index(op.f('ix_family_relations_zone_id'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_validation_status'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_target_person_id'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_sync_status'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_source_person_id'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_relation_type'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_campaign_id'), table_name='family_relations')
    op.drop_table('family_relations')
    op.drop_index(op.f('ix_duplicate_candidates_status'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_person_b_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_person_a_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_created_at'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_index(op.f('ix_documents_person_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_local_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_receiver_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('chat_groups')
    op.drop_table('chat_group_members')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attachments_sync_status'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_local_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_attachment_type'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_assignments_zone_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_app_roles_name'), table_name='app_roles')
    op.drop_table('app_roles')
    # ### end Alembic commands ###
