"""Add chat message reply and reactions

Revision ID: c2d01180e204
Revises: 
Create Date: 2026-07-18 15:43:35.343233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c2d01180e204'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('reply_to', sa.String(length=64), nullable=True))
    op.add_column('chat_messages', sa.Column('reactions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'reactions')
    op.drop_column('chat_messages', 'reply_to')
    # ### end Alembic commands ###
