import sys
import alembic.config

def main():
    """Run alembic upgrade head"""
    print("Running database migrations...")
    alembic_args = ["upgrade", "head"]
    alembic.config.main(argv=alembic_args)

def makemigrations():
    """Run alembic revision --autogenerate"""
    if len(sys.argv) < 2:
        print("Usage: poetry run africensus-makemigrations 'migration message'")
        sys.exit(1)
    
    msg = sys.argv[1]
    print(f"Creating autogenerated migration: {msg}")
    alembic_args = ["revision", "--autogenerate", "-m", msg]
    alembic.config.main(argv=alembic_args)

def reset():
    """Reset database, delete migrations and trigger seed."""
    import os
    import glob
    from sqlalchemy import text
    from app.database import Base, engine, SessionLocal
    from app.init_db import init_db

    print("Cleaning migration files...")
    versions_dir = os.path.join("alembic", "versions")
    if os.path.exists(versions_dir):
        for f in glob.glob(os.path.join(versions_dir, "*.py")):
            os.remove(f)
        print("Migration files deleted.")

    print("Dropping all tables...")
    Base.metadata.drop_all(bind=engine)
    
    with engine.connect() as conn:
        try:
            conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
            conn.commit()
        except Exception:
            pass

    print("Creating all tables via migrations...")
    # Generate initial migration
    print("Generating initial migration...")
    alembic.config.main(argv=["revision", "--autogenerate", "-m", "Initial schema"])
    
    # Apply migration
    print("Applying migration...")
    alembic.config.main(argv=["upgrade", "head"])

    print("Seeding database...")
    with SessionLocal() as db:
        init_db(db)
    
    print("Database has been fully reset, migrated, and seeded!")

def seed():
    """Seed the database with initial data without dropping tables."""
    from app.database import SessionLocal
    from app.init_db import init_db
    
    print("Seeding database...")
    with SessionLocal() as db:
        init_db(db)
    print("Seeding completed successfully!")
